import { PROFILE_VERSION, type PerspectiveProfile } from "./types";
const rows = [
  [
    "landscape",
    "Landschaftsarchitektur / Freiraum",
    "professional",
    "green|blue|land-use",
    "Welche Freiraumqualitäten sollten vor Ort geprüft werden?",
    "Freiraum,Zugänglichkeit",
  ],
  [
    "planning",
    "Stadt- und Regionalplanung",
    "professional",
    "fua|district|land-use",
    "Wie passen Projekt und räumliches Umfeld zusammen?",
    "Maßstab,Nutzungsmischung",
  ],
  [
    "ecology",
    "Ökologie und Klima",
    "professional",
    "tree|green|sun|water",
    "Welche Klima- und Artenschutzfragen erfordern zusätzliche lokale Erhebungen?",
    "Habitat,Hitze,Wasser",
  ],
  [
    "mobility",
    "Mobilität",
    "professional",
    "street|transport|mobility|station",
    "Welche Wege und Barrieren sollten mit Nutzer:innen überprüft werden?",
    "Erreichbarkeit,Barriere",
  ],
  [
    "health",
    "Gesundheit",
    "professional",
    "health|green|poi",
    "Welche gesundheitlichen Belastungen und Ressourcen sind noch zu erheben?",
    "Gesundheit,Erholung",
  ],
  [
    "everyday",
    "Soziales und Alltag",
    "professional",
    "population|housing|poi",
    "Welche Alltagsnutzungen werden in den vorliegenden Daten nicht sichtbar?",
    "Alltag,Teilhabe",
  ],
  [
    "administration",
    "Verwaltung und Zuständigkeit",
    "institutional",
    "boundary|district",
    "Welche Zuständigkeiten und Prüfverfahren müssen geklärt werden?",
    "Zuständigkeit,Verfahren",
  ],
  [
    "politics",
    "Politik und Aushandlung",
    "institutional",
    "",
    "Welche Ziele müssen öffentlich ausgehandelt werden?",
    "Aushandlung,Entscheidung",
  ],
  [
    "ownership",
    "Eigentum / Projektentwicklung",
    "institutional",
    "",
    "Welche Eigentums- und Ressourcenannahmen sind unbestätigt?",
    "Eigentum,Ressourcen",
  ],
  [
    "recognition",
    "Nicht organisierte / unterrepräsentierte Betroffenheit",
    "participation",
    "",
    "Wer konnte bislang nicht mitsprechen, und welche barrierearmen Beteiligungswege fehlen?",
    "Anerkennung,Beteiligungsmöglichkeit",
  ],
] as const;
export const profiles: PerspectiveProfile[] = rows.map(
  ([id, name, category, pattern, question, terms]) => ({
    id,
    name,
    category,
    scope:
      "Reflexion des gewählten Falls; keine fachliche Prüfung oder Gruppenvertretung",
    questions: [question],
    terms: terms.split(","),
    indicatorPatterns: pattern ? [pattern] : [],
    interactions: ["Ziele und vorgeschlagene Intervention gemeinsam prüfen"],
    limits: [
      "Keine authentische Vertretung betroffener Gruppen.",
      "Ohne lokale Evidenz nur allgemeine Prüffragen.",
    ],
    knowledgeRefs: [],
    version: PROFILE_VERSION,
    reviewStatus: "editorial-draft",
    dimensions: {
      expertise: category === "professional" ? name : "offen",
      institution: category === "institutional" ? name : "offen",
      affectedness: "im Fall zu erheben",
      decisionPower: "nicht aus Berufsrolle ableitbar",
      recognition: "auch nicht organisierte Betroffenheit prüfen",
      participation: "von Betroffenen selbst zu bestimmen",
    },
  }),
);
export const FACTORS = [
  ["location", "Lage und Erschließung", "fua|district|street"],
  ["culture", "Geschichte, Kultur und Umfeld", "culture|heritage"],
  ["services", "Wohnen und Daseinsvorsorge", "housing|education|health|poi"],
  ["mobility", "Mobilität und Barrieren", "mobility|transport|barrier|station"],
  ["climate", "Klima, Wasser und Stadtgrün", "sun|green|blue|tree"],
  ["nature", "Natur- und Artenschutz", "species|habitat"],
  [
    "demographics",
    "Soziodemografie und Betroffenheit",
    "population|age|demograph",
  ],
  ["planning", "Planungsgrundlagen und Zuständigkeiten", "planning-law"],
  ["economy", "Wirtschaft und Eigentum", "ownership"],
  ["projects", "Projekte und bekannte Konflikte", "verified-project"],
] as const;
